### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by vinny0212** [Puntzi/pnt_blackMarket#1]
Does it happen to have a bug with buying items? with me I don't get any items in my inventory....

**Comment by Puntzi** [comment]
Actually i tested now, and it's working for me, remember that the second parameter of the config items need to be the same as sql item

**Comment by IamPatrikexe** [comment]
> Does it happen to have a bug with buying items? with me I don't get any items in my inventory....

Maybe that item is not existing in your sql database.
